version: '3.8'

services:
  postgres:
    image: bitnami/postgresql:latest
    container_name: postgres_container
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_DATABASE=db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/bitnami/postgresql

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      - PGADMIN_DEFAULT_EMAIL=lfbalaminute@hotmail.com
      - PGADMIN_DEFAULT_PASSWORD=28012004Lf@pgadmin
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  postgres_data:
    driver: local